import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";
import { join } from "node:path";

const root = process.cwd();
const envPath = join(root, ".env.local");

function parseEnv(content) {
  const values = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const index = line.indexOf("=");
    if (index < 1) continue;
    const key = line.slice(0, index).trim();
    let value = line.slice(index + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

function randomPassword() {
  return "Anchor-" + randomBytes(9).toString("base64url") + "!";
}

const existing = existsSync(envPath)
  ? parseEnv(readFileSync(envPath, "utf8"))
  : {};

const values = {
  ...existing,
  DATABASE_URL:
    existing.DATABASE_URL || "postgres://anchor:anchor@localhost:5432/anchor",
  DATABASE_SSL: existing.DATABASE_SSL || "false",
  AUTH_SECRET:
    existing.AUTH_SECRET || randomBytes(48).toString("base64url"),
  NEXT_PUBLIC_SITE_URL:
    existing.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  ANCHOR_DEMO_MODE: existing.ANCHOR_DEMO_MODE || "false",
  SEED_ADMIN_EMAIL:
    existing.SEED_ADMIN_EMAIL || "admin@anchor.local",
  SEED_ADMIN_PASSWORD:
    existing.SEED_ADMIN_PASSWORD || randomPassword(),
  SEED_ORG_NAME:
    existing.SEED_ORG_NAME || "Anchor Demo District",
  SEED_ORG_SLUG:
    existing.SEED_ORG_SLUG || "anchor-demo",
  CRON_SECRET:
    existing.CRON_SECRET || randomBytes(32).toString("base64url"),
};

const orderedKeys = [
  "DATABASE_URL",
  "DATABASE_SSL",
  "AUTH_SECRET",
  "NEXT_PUBLIC_SITE_URL",
  "ANCHOR_DEMO_MODE",
  "SEED_ADMIN_EMAIL",
  "SEED_ADMIN_PASSWORD",
  "SEED_ORG_NAME",
  "SEED_ORG_SLUG",
  "CRON_SECRET",
];

const preservedKeys = Object.keys(values).filter(
  (key) => !orderedKeys.includes(key),
);

const lines = [
  "# Generated by npm run setup:local. This file is gitignored.",
  ...orderedKeys.map((key) => key + "=" + values[key]),
  ...preservedKeys.map((key) => key + "=" + values[key]),
  "",
];

writeFileSync(envPath, lines.join("\n"), { mode: 0o600 });

console.log("\nAnchor local setup");
console.log("------------------");
console.log("Environment written to .env.local");

const dockerCheck = spawnSync("docker", ["compose", "version"], {
  cwd: root,
  stdio: "ignore",
});

if (dockerCheck.status !== 0) {
  console.error(
    "\nDocker Compose is not available. Start/install Docker Desktop, then run npm run setup:local again.",
  );
  process.exit(1);
}

const up = spawnSync("docker", ["compose", "up", "-d", "postgres"], {
  cwd: root,
  stdio: "inherit",
});
if (up.status !== 0) process.exit(up.status ?? 1);

let ready = false;
for (let attempt = 0; attempt < 30; attempt += 1) {
  const check = spawnSync(
    "docker",
    ["compose", "exec", "-T", "postgres", "pg_isready", "-U", "anchor", "-d", "anchor"],
    { cwd: root, stdio: "ignore" },
  );
  if (check.status === 0) {
    ready = true;
    break;
  }
  await new Promise((resolve) => setTimeout(resolve, 1000));
}

if (!ready) {
  console.error("\nPostgreSQL did not become ready within 30 seconds.");
  process.exit(1);
}

for (const command of [
  ["run", "db:migrate"],
  ["run", "db:seed"],
]) {
  const result = spawnSync("npm", command, {
    cwd: root,
    stdio: "inherit",
    env: { ...process.env, ...values },
  });
  if (result.status !== 0) process.exit(result.status ?? 1);
}

console.log("\nLocal Anchor workspace is ready.");
console.log("URL:      http://localhost:3000");
console.log("Email:    " + values.SEED_ADMIN_EMAIL);
console.log("Password: " + values.SEED_ADMIN_PASSWORD);
console.log("Org slug: " + values.SEED_ORG_SLUG);
console.log("\nNow run: npm run dev\n");
