import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { spawnSync } from "node:child_process";
import { join } from "node:path";

const root = process.cwd();
const envPath = join(root, ".env.local");

function parseEnv(content) {
  const values = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const index = line.indexOf("=");
    if (index < 1) continue;
    const key = line.slice(0, index).trim();
    let value = line.slice(index + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

function randomPassword() {
  return "Yumna-" + randomBytes(9).toString("base64url") + "!";
}

const existing = existsSync(envPath) ? parseEnv(readFileSync(envPath, "utf8")) : {};
const values = {
  ...existing,
  DATABASE_URL: existing.DATABASE_URL || "postgres://operator:operator@localhost:5432/operator",
  DATABASE_SSL: existing.DATABASE_SSL || "false",
  AUTH_SECRET: existing.AUTH_SECRET || randomBytes(48).toString("base64url"),
  NEXT_PUBLIC_SITE_URL: existing.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  OPERATOR_DEMO_MODE: existing.OPERATOR_DEMO_MODE || "true",
  CRON_SECRET: existing.CRON_SECRET || randomBytes(32).toString("base64url"),
  SEED_ADMIN_EMAIL: existing.SEED_ADMIN_EMAIL || "admin@yumna.local",
  SEED_ADMIN_PASSWORD: existing.SEED_ADMIN_PASSWORD || randomPassword(),
  SEED_ORG_NAME: existing.SEED_ORG_NAME || "Yumna Demo",
  SEED_ORG_SLUG: existing.SEED_ORG_SLUG || "yumna-demo",
};

const orderedKeys = [
  "DATABASE_URL",
  "DATABASE_SSL",
  "AUTH_SECRET",
  "NEXT_PUBLIC_SITE_URL",
  "OPERATOR_DEMO_MODE",
  "CRON_SECRET",
  "SEED_ADMIN_EMAIL",
  "SEED_ADMIN_PASSWORD",
  "SEED_ORG_NAME",
  "SEED_ORG_SLUG",
];
const preservedKeys = Object.keys(values).filter((key) => !orderedKeys.includes(key));
writeFileSync(
  envPath,
  ["# Generated by npm run setup:local. This file is gitignored.", ...orderedKeys.map((key) => key + "=" + values[key]), ...preservedKeys.map((key) => key + "=" + values[key]), ""].join("\n"),
  { mode: 0o600 },
);

console.log("\nYumna local setup");
console.log("--------------------");
console.log("Environment written to .env.local");

const dockerCandidates = [
  "docker",
  "/Applications/Docker.app/Contents/Resources/bin/docker",
  join(process.env.HOME || "", "Applications/Docker.app/Contents/Resources/bin/docker"),
].filter(Boolean);

let dockerBin = null;
for (const candidate of dockerCandidates) {
  const check = spawnSync(candidate, ["compose", "version"], { cwd: root, stdio: "ignore" });
  if (check.status === 0) { dockerBin = candidate; break; }
}
if (!dockerBin) {
  console.error("\nDocker CLI / Compose could not be found. Start Docker Desktop and rerun npm run setup:local.");
  process.exit(1);
}
if (spawnSync(dockerBin, ["info"], { cwd: root, stdio: "ignore" }).status !== 0) {
  console.error("\nDocker was found, but its engine is not ready.");
  process.exit(1);
}
const up = spawnSync(dockerBin, ["compose", "up", "-d", "postgres"], { cwd: root, stdio: "inherit" });
if (up.status !== 0) process.exit(up.status ?? 1);

let ready = false;
for (let attempt = 0; attempt < 30; attempt += 1) {
  const check = spawnSync(dockerBin, ["compose", "exec", "-T", "postgres", "pg_isready", "-U", "operator", "-d", "operator"], { cwd: root, stdio: "ignore" });
  if (check.status === 0) { ready = true; break; }
  await new Promise((resolve) => setTimeout(resolve, 1000));
}
if (!ready) {
  console.error("\nPostgreSQL did not become ready within 30 seconds.");
  process.exit(1);
}

for (const command of [["run", "db:migrate"], ["run", "db:seed"]]) {
  const result = spawnSync("npm", command, { cwd: root, stdio: "inherit", env: { ...process.env, ...values } });
  if (result.status !== 0) process.exit(result.status ?? 1);
}

console.log("\nLocal Yumna workspace is ready.");
console.log("URL:      http://localhost:3000");
console.log("Email:    " + values.SEED_ADMIN_EMAIL);
console.log("Password: " + values.SEED_ADMIN_PASSWORD);
console.log("Org slug: " + values.SEED_ORG_SLUG);
console.log("\nNow run: npm run dev\n");
