import { requireSession } from "@/lib/auth";
export const dynamic = "force-dynamic";
const connections = [
  { name: "Browser & API runner", env: "OPERATOR_ACTION_RUNNER_URL", connected: Boolean(process.env.OPERATOR_ACTION_RUNNER_URL), description: "Live web research, forms, merchant APIs, calendars, bookings and payment initiation." },
  { name: "Voice agent", env: "OPERATOR_VOICE_AGENT_URL / Twilio", connected: Boolean(process.env.OPERATOR_VOICE_AGENT_URL || (process.env.TWILIO_ACCOUNT_SID && process.env.TWILIO_AUTH_TOKEN && process.env.TWILIO_FROM_NUMBER)), description: "Outbound calls, hold time and real conversations with businesses." },
  { name: "Email", env: "RESEND_API_KEY", connected: Boolean(process.env.RESEND_API_KEY && process.env.RESEND_FROM_EMAIL), description: "Transactional messages and follow-up email." },
  { name: "Human escalation", env: "OPERATOR_HUMAN_QUEUE_URL", connected: Boolean(process.env.OPERATOR_HUMAN_QUEUE_URL), description: "Exception queue when automation should hand off to a trained operator." },
  { name: "Demo executor", env: "OPERATOR_DEMO_MODE", connected: process.env.OPERATOR_DEMO_MODE === "true", description: "Completes workflows locally without making external changes." },
];
export default async function ConnectionsPage() { await requireSession(); return <div className="operator-page"><header className="operator-page-header"><div><span className="operator-kicker">Connections</span><h1>The outside world, connected.</h1><p>The application is complete behind these contracts. Production credentials and provider endpoints turn each capability live without changing the task engine.</p></div></header><section className="operator-connection-grid">{connections.map((connection) => <article key={connection.name}><div className="operator-connection-state"><span className={connection.connected ? "connected" : ""} />{connection.connected ? "Connected" : "Needs connection"}</div><h2>{connection.name}</h2><p>{connection.description}</p><code>{connection.env}</code></article>)}</section></div>; }
